baseURL = "https://adityasaini.in/blog/"
languageCode = "en-us"
title = "Aditya Saini's blog"
theme = "kiera"
publishdir = "../blog/"
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[author]
    name = "Aditya Saini"

[params]
    tagline = "Pure Computer Science Knowledge Portal"
